### ISSUE TITLE
Work-around that CyPari2 has removed prec_words_to_dec

### ISSUE THREAD

**Issue by NathanDunfield** [3-manifolds/SnapPy#124]
With the newest version 2.2.0 of `cypari2` importing `snappy` results in the below error.  It seems that CyPari2 has removed `prec_words_to_dec`.   SnapPy uses that function to estimate how many digits of the decimal representation of a volume are correct.  Only when running in Sage does SnapPy use CyPari2 (otherwise it uses CyPari).  This only affects people using SnapPy in the not-yet released Sage 10.5.

```
Traceback (most recent call last):
 File "/usr/bin/SnapPy", line 33, in <module>
   sys.exit(load_entry_point('snappy==3.1.1', 'console_scripts',
'SnapPy')())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File
"/usr/bin/SnapPy", line 25, in importlib_load_entry_point return
next(matches).load() ^^^^^^^^^^^^^^^^^^^^
 File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 205,
in load module = import_module(match.group('module'))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/usr/lib/python3.12/importlib/__init__.py", line 90, in
import_module return _bootstrap._gcd_import(name[level:], package,
level) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
 File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
 File "<frozen importlib._bootstrap>", line 1310, in
_find_and_load_unlocked File "<frozen importlib._bootstrap>", line 488,
in _call_with_frames_removed File "<frozen importlib._bootstrap>", line
1387, in _gcd_import File "<frozen importlib._bootstrap>", line 1360,
in _find_and_load File "<frozen importlib._bootstrap>", line 1331, in
_find_and_load_unlocked File "<frozen importlib._bootstrap>", line 935,
in _load_unlocked File "<frozen importlib._bootstrap_external>", line
995, in exec_module File "<frozen importlib._bootstrap>", line 488, in
_call_with_frames_removed File
"/usr/lib/python3.12/site-packages/snappy-3.1.1-py3.12-linux-x86_64.egg/snappy/__init__.py",
line 6, in <module> from .SnapPy import (AbelianGroup, File
"cython/numbers/double.pyx", line 1, in init SnapPy File
"/usr/lib/python3.12/site-packages/snappy-3.1.1-py3.12-linux-x86_64.egg/snappy/number.py",
line 6, in <module> from .pari import * File
"/usr/lib/python3.12/site-packages/snappy-3.1.1-py3.12-linux-x86_64.egg/snappy/pari.py",
line 17, in <module> from cypari2.pari_instance import
(prec_words_to_dec, ImportError: cannot import name 'prec_words_to_dec'
from 'cypari2.pari_instance'
(/usr/lib/python3.12/site-packages/cypari2/[pari_instance.cpython-312-x86_64-linux-gnu.so](http://pari_instance.cpython-312-x86_64-linux-gnu.so/)).
Did you mean: 'prec_bits_to_dec'?
```

**Comment by culler** [comment]
Maybe this problem is going to vanish.

With Sage 10.5beta8 I am seeing no errors when importing the precision converters:
```
sage: from cypari2.pari_instance import prec_words_to_dec
sage: from cypari2.pari_instance import prec_words_to_bits
sage: from cypari2.pari_instance import prec_bits_to_dec
sage: from cypari2.pari_instance import prec_dec_to_bits
```
I think that may mean that those functions have been restored in CyPari2, presumably for compatibility reasons.

**Comment by NathanDunfield** [comment]
What version of `cypari2` does `10.5beta8` come with?  I'm not seeing any substantial [commits to cypari2](https://github.com/sagemath/cypari2/commits/master/) since they released `cypari 2.2.0`.  Could it have to do with the underlying version of Pari itself?

**Comment by culler** [comment]
It comes with CyPari 2.2.0 and Pari 2.15.4.  There has been a lot of activity at CyPari2 related to precision issues with Pari 2.17.  So I would guess that it does indeed have to do with the version of Pari.

**Comment by culler** [comment]
Maybe the workaround, for now, is to use CyPari2 from Sage rather than installing the bleeding edge on top of Sage's version.

**Comment by NathanDunfield** [comment]
The report came from a user of the Arch Linux distro, which does rolling releases and currently has Pari 2.17.

**Comment by culler** [comment]
I looked at the cypari github site, and as far as I can tell, they have not removed prec_words_to_dec.  They did make several changes to accommodate pari 2.17, but those changes did not include removing that function from the pari_instance module.  On the other hand, [this page](https://archlinux.org/packages/extra/x86_64/pari/) indicates that the Arch linux pari package is using Pari 2.17.

I suspect that when Arch switched to pari 2.17 the maintainer of the Arch Sage package was forced to do his own adaptation of cypari2 to pari 2.17, and he chose to delete pari_words_to_dec and thereby break SnapPy in Arch sage 10.4.

So it is not clear to me what we should do.  We could modify SnapPy to avoid using prec_words_to_dec now.  That would accommodate a random choice made by the Arch maintainer.  But after cypari2 does its next release, and after sage incorporates that release into sage, the current SnapPy code will work again.  So the change is not necessary, except for the purpose of making snappy work on one release of sage for one linux distro which happened to make an incompatible change to the cypari2 package.

I think that may mean that we should do nothing.

**Comment by NathanDunfield** [comment]
@culler Unfortunately, I believe this [cypari2 PR to support Pari 2.17](https://github.com/sagemath/cypari2/pull/166) will remove `prec_words_to_dec` and will be merged shortly.  Let's see if they are amendable to keeping it.

**Comment by NathanDunfield** [comment]
They are open to keeping `prec_words_to_dec` and friends, at least for Pari 2.15, but it's not clear whether they would work for Pari 2.17.  It looks like we use these three times in submodules of `verify`, a few times in `number`, and also in `snap.shapes`.  Thoughts?  Also, tagging @unhyperbolic as the author of `verify`.

**Comment by culler** [comment]
I think we should just implement a replacement for prec_words_to_dec as a
function defined within SnapPy.  SnapPy no longer supports 32 bit
platforms, which means that we know that a Pari word is 64 bits on any
machine which could run SnapPy.  So it is trivial to compute the base 10
precision from the base 2^64 precision, which in turn is equal to
gen.wordsize() - 2 for a gen of type T_REAL or T_COMPLEX.

- Marc

**Comment by culler** [comment]
I think this is fixed in my latest commit.  To test, I used %pip to install cypari2-2.2.1 in SageMath-10.5.  Then I installed SnapPy from the current tip of our repo in SageMath-10.5.  Then this is what I see:
```
% sage
┌────────────────────────────────────────────────────────────────────┐
│ SageMath version 10.5, Release Date: 2024-12-04                    │
│ Using Python 3.12.5. Type "help()" for help.                       │
└────────────────────────────────────────────────────────────────────┘
sage: import cypari2
sage: cypari2.prec_words_to_dec
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[2], line 1
----> 1 cypari2.prec_words_to_dec

AttributeError: module 'cypari2' has no attribute 'prec_words_to_dec'
sage: import snappy
sage: M = snappy.Manifold('m125')
sage: v = M.volume(bits_prec=1024)
sage: snappy.number.Number(v).accuracy
308
```

**Comment by tornaria** [comment]
Please see my comment https://github.com/3-manifolds/SnapPy/commit/7f0bac4d1a23d1c478ba1cd433e9a479a8c6e3bd#r150980881

**Comment by tornaria** [comment]
Also, I think for a little while there was a cypari 2.2.1 in pypi with this function removed, but the function was restored (with a deprecated warning).

**Comment by NathanDunfield** [comment]
> Also, I think for a little while there was a cypari 2.2.1 in pypi with this function removed, but the function was restored (with a deprecated warning).

Here "this function" refers to `prec_bits_to_dec`?

**Comment by tornaria** [comment]
> > Also, I think for a little while there was a cypari 2.2.1 in pypi with this function removed, but the function was restored (with a deprecated warning).
> 
> Here "this function" refers to `prec_bits_to_dec`?

I meant `prec_words_to_dec`. The functions to convert bits to dec were never removed (they are just multiplication by lg(10) or so)

**Comment by NathanDunfield** [comment]
I checked that the commit aae6a4641dc works on Arch Linux, which already has PARI 2.17 and no `prec_words_to_dec` function.  Closing the ticket.
